### ISSUE TITLE
Automated builds with version numbered Unity binary

### ISSUE THREAD

**Issue by giantotter** [giantotter/giantotter_public#1]

**Comment by grahamboree** [comment]
We want to set up a build system that automatically makes builds, and deploys them to prealpha.giantotter.com.  The script already exists to do this, but this task involves setting up Jenkins, having the script be triggered by jenkins when we tell it (we don't want every single build to be uploaded).  We also want to set up a test scenario, possibly using the Integration testing framework in Unity's Test Tools to test various aspects of the build, like interacting with items.  We'd want Jenkins to compile the code, and run these tests on every checkin.  Also if there are any unit tests, they should be run after every checkin as well.

**Comment by jefforkin** [comment]
Also detect major and minor current version.  prompt user when major version changes.
