### ISSUE TITLE
Multiplayer does not track spawned food items after they have been eaten once

### ISSUE THREAD

**Issue by tomaschko** [giantotter/giantotter_public#104]
As a waitress, order wine or salmon. Put the item on the table for the customer so that the customer sees the full plate or glass on the table. Eat the item at least once. Then take it away or eat all of the food / drink all of the wine. The customer will still see a full plate / glass (minus one bite / sip I think)

**Comment by jefforkin** [comment]
I was not able to repro.  I tried ordering a glass of red wine, putting it on a table, taking a sip, then picking it up.  both players saw the pick up, and both players saw as I took more sips until it was empty.  Tried same thing with Salmon, but also did not see the bug.

**Comment by tomaschko** [comment]
Tried 2x to reproduce and couldn't, so I'm going to close for now. I'll reopen if I can find the specific conditions that caused the issue initially
