### ISSUE TITLE
Customer walks to different point on two clients

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#106]
In multiplayer, a player can end up standing somewhere different on two different clients.

Repro:
- connect customer and waitress.
- move waitress away form podium.
- have customer create a bill at podium.
- customer tries to look at new bill that is now sitting on the podium.
- you should see the clone customer walk to the other side of the podium.

**Comment by grahamboree** [comment]
Can't repro. :disappointed:
