### ISSUE TITLE
Implement mechanism to influence who you are paired with

### ISSUE THREAD

**Issue by giantotter** [giantotter/giantotter_public#11]

**Comment by tomaschko** [comment]
If a user joins a public multiplayer game with no preference on role, he should be assigned the role that maximizes his chances of being paired. 

Decision could be something like

    If a user is waiting, assign roles to complete the pairing

    Else, assign the role that is less likely to be picked by the next user expressing a preference 

(We would need to dig into the data to determine this. We could hardcode and update periodically. Or we could create a stochastic variable based on preferences over the past week or month)

**Comment by grahamboree** [comment]
There was originally a system in place to do this when we used the database as the multiplayer backend, however it wasn't carried over.  This would be doable if we changed the way the matchmaking works such that it can detect who's waiting, and choose the first role that lets them be paired.
