### ISSUE TITLE
Tap and hold to interact in mobile

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#118]
The user should tap and hold to interact on mobile, rather than double-tap.  

As part of this, there needs to be an interaction UI item that pops up with an indication that it's waiting for the tap to be held for some amount of time.  We've talked about a circular, ring indicator that radially fills up while  your finger is pressed and stationary.

The tap and hold motion should only take about .2-.4 seconds, but having the tap and hold interaction take a certain amount of time makes it distinguishable from the tap and drag to look around.

e.g. [Destiny does this (probably for networking reasons)](https://www.youtube.com/watch?v=NxMlqXT2CtI&t=1m41s)

**Comment by jefforkin** [comment]
no longer relevant
