### ISSUE TITLE
Implement text field requirement check in new UI

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#121]
In the old UI you could mark a text field as 'required'.  This would prevent the player from advancing to the next page in the UI unless they'd entered data in that text field.

The new UI still supports tagging text fields as 'required,' however it does not check that all required text fields are not blank when progressing to the next page.

**Comment by grahamboree** [comment]
AFAIK this was only used in the Lemelson build.  It's not used in the current TRG build.

**Comment by jefforkin** [comment]
no longer relevant
