### ISSUE TITLE
Tutorial: After looking at menu, controls no longer work

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#122]
After looking the menu in the tutorial, and dismissing a tutorial dialogue, controls no longer work.  Can't move around anymore.

**Comment by jefforkin** [comment]
Note that I have temporarily given the Actions_Menu prefab the default LookAt action to as a workaround so that the tutorial can keep going.

**Comment by grahamboree** [comment]
This, along with #127, #112 and #113 are all symptoms of the same underlying problem, so I'm pulling them all in to in-progress as well, despite them not being on this sprint.
