### ISSUE TITLE
Lookat sometimes leaves the head rotation incorrectly offset

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#126]
When a lookat action is performed and the full range of head motion and rotation is mostly (but not fully) possible, the lookat will complete, but the final head rotation will not match the starting head rotation.  This causes the head to be offset such that the 'forward' direction according to the head is different than the direction of movement.  

Repro:

1.  Pick up an item
2.  Click on the item that is held and select "look at".
3.  Wait for the animation to finish completely.
4.  Look towards a distant point and press W or the up arrow to walk forwards.
5.  Observe the character's movement direction.  The yaw angle is offset by the amount of rotation the head was unable to do when performing the lookat.

**Comment by dwenger01** [comment]
This should be fixed with the "Fix look-at rotation issues" patch.
( SHA key = aaa9e7b6eb5f3ecccdfe56664f448a1f116e8464 )
