### ISSUE TITLE
Tutorial: Can't click the "Begin" button after the sitting step.

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#127]
The mouse is locked and the window's button is unclickable.   I have a feelling this has to do with the order of operations.  The window is disabling the mouse controls and unlocking the mouse, but the sit controls are re-enabling mouse look after the window is shown and the sit motion finishes.

**Comment by jefforkin** [comment]
Re-assigning to Graham, because it is UI related.  After sitting, the mouse is locked in the middle of the screen, and moving the mouse controls headlook.  I can hit esc, dismiss the settings menu, and then am able to click Begin on the tutorial step.

**Comment by jefforkin** [comment]
Note -- the tutorial has changed, such that it is no longer necessary to click the Begin button.  However, there is still an intermittent issue, where after sitting or standing, sometimes the mouse is not locked when it should be.   But, it might make sense to hold off on trying to fix this until Dave has completed any changes/fixes to sit.
