### ISSUE TITLE
Triggering a GOTO while sitting causes your body to move while the camera stays stationary.

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#128]
Repro:
* Sit in a chair
* Click on an interactable object across the room and select 'GOTO'
* Observe your body fly across the room.

**Comment by grahamboree** [comment]
![headless](https://cloud.githubusercontent.com/assets/1139220/8586641/014d8132-25bf-11e5-9d8a-0b2e7267be77.png)

**Comment by dwenger01** [comment]
I'd suggest that a goto while seated should cause the player to stand, but not go anywhere.  Thoughts?

**Comment by jefforkin** [comment]
I agree.  This would be the easiest solution.  Someday in the future, if we really want to, we could implement some kind of action queue to have someone start the GOTO after standing, but I don't think this is a priority.  Just doing the stand would eliminate the more obvious bug.
