### ISSUE TITLE
chat UI blocks interacting with objects

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#130]

**Comment by tomaschko** [comment]
I have a note on a bug (I think from Clark): "A chat message from the other user would cause the interaction menu to disappear before I could select an action" ... something like that

Does this issue refer to that? Or is this only about the screen real estate issue?

**Comment by jefforkin** [comment]
Your note from Clark is a separate bug.  My bug refers to the fact that (when playing on the web, not fullscreen), the chat UI elements often block the middle of the screen where the interaction cursor is.
