### ISSUE TITLE
Esc key exits fullscreen, when trying to show settings

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#136]
This is the way Unity webplayer works, so we need to consider a different way to bring up the settings menu.

**Comment by grahamboree** [comment]
Starcraft 2 uses F10 as a "settings" button , because Escape is used as part of the player's in-game controls (cancelling an order).  I think they also do this so it's hard to hit accidentally.  We could do something similar with an F key, and indicate which one it is on screen somewhere.

**Comment by jefforkin** [comment]
F10 sounds good to me, if there is already a precedent.  We can put something in the bottom right, indicating that F10 --> Settings.  Since we no longer have the icons there.

**Comment by grahamboree** [comment]
Changed to F10 and added an on-screen reminder of which key it is.  Modeled exactly after starcraft 2.
