### ISSUE TITLE
Players can't move/rotate at same time in multiplayer

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#140]
Dave reported he and Brynda could not move or rotate at the same time.

**Comment by jefforkin** [comment]
Dan & Jeff will try to repro this

**Comment by grahamboree** [comment]
Any luck reproing this?

**Comment by jefforkin** [comment]
I had trouble reproing it myself with two windows on the same machine.  Dan and I never really tried to repro from separate machines, so it might be worth a quick test.  Or we could close it until anyone complains about it in the future.

**Comment by dwenger01** [comment]
Never saw this again after that first playtest.  I could not repro again either, even with 2 different machines.  (Bryn and I were both logged in as me in that first playtest).

**Comment by grahamboree** [comment]
Should we close it for now, until someone reports it again?
