### ISSUE TITLE
Player walks to different spot on local & remote client

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#148]
Dan reported that players were on opposite sides of the counter.

I've seen this when a player tries to look at a bill on the podium.  Local player stays still.  Remote walks around to other side of podium.

Aside from understanding/fixing the bug, we might want all actions to forcibly sync the actor's position & orientation at the start of an action, to account for navigational drift related to asynchronous networking.

**Comment by grahamboree** [comment]
Also can't repro :disappointed: 

The fact that a character is walking to the other side of the kitchen counter is in itself a broader issue that deserves more thought.
