### ISSUE TITLE
Migrating player's camera to new camera manager

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#150]

**Comment by jefforkin** [comment]
Can we move this to the backlog for now? Seems like we're not focusing on cameras in the immediate future.

**Comment by dwenger01** [comment]
Yes.  I haven't been actively working on the camera stuff for a little while now, and we'll probably want to re-evaluate where we're at anyway.

**Comment by jefforkin** [comment]
no longer relevant
