### ISSUE TITLE
Interaction UI requires extra clicks after reload

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#156]
After the game reloads back to the Main Menu, next time I run the level, it takes two clicks to dismiss the interaction UI (like, click Use twice).  If I reload again, it takes 3 clicks.

To repro, you can hack a reload instruction into a tutorial script:
        "instructions": [
            {
                "type": "restart"
            }
        ]

**Comment by grahamboree** [comment]
Yeah.... this has to do with the static data members I was mentioning the other day.   Definitely something I need to fix.
