### ISSUE TITLE
When playing the tutorial as a Customer, the sample other player chat text appears as your own

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#167]

**Comment by grahamboree** [comment]
![capture](https://cloud.githubusercontent.com/assets/1139220/8737413/cd2baa96-2bef-11e5-9130-ff5a34c81786.PNG)

**Comment by jefforkin** [comment]
good catch. I checked in a fix in code, but can't update oscript until the next build is live, without breaking the tutorial.

**Comment by grahamboree** [comment]
We can make a build tomorrow and update the oscript.
