### ISSUE TITLE
Clicking to exit chat should not show interaction menu

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#169]
If I chat to the bartender, then click the screen to exit chat, I am not really want to interact with the bartender, so it is annoying to have to close the interaction UI.

Eventually we should have a different cursor for mouse-locked interaction, and clicking the screen after chatting should toggle back to that cursor, but but not trigger an interaction until the next click.

**Comment by grahamboree** [comment]
Agreed.  This shouldn't happen.  Good catch.
