### ISSUE TITLE
Build bot should be able to perform the entire build process.

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#170]
* Get the latest code
* Generate the build notes
* Update the build notes web page and check in the change.
* Build the game
* Upload the game and buildnotes page to s3 and 'set public' on them
* Invalidate the cloudfront cache
* Post build notes to slack and notify the team that a new build is live.

**Comment by jefforkin** [comment]
Would be great to combine this with the task(s) related to auto-updating the build number, displaying it on-screen, and using it on the unity binary filename (to avoid caching issues, but also requiring the web page hosting the webplayer to be updated).

**Comment by grahamboree** [comment]
Good idea.  We'd probably want to have some api call or something that would tell the webpage what version of the webplayer to load, otherwise I think we'd have to clear the cache anyway to get the webpage to update.
