### ISSUE TITLE
Mouse pointer does not appear in navigation mode on Mac webplayer

### ISSUE THREAD

**Issue by tomaschko** [giantotter/giantotter_public#171]
When I'm looking around or walking around, the mouse pointer disappears. When I want to interact with an object I have to guess what I'm looking at - I should have a mouse pointer to indicate the center of the screen and the object I am interacting with

**Comment by grahamboree** [comment]
This will be fixed with the reticle from #120.  Currently it's a limitation of the OSX webplayer that we can't easily work around.
