### ISSUE TITLE
Sitting on what you're holding prevents you from moving.

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#188]

**Comment by dwenger01** [comment]
If you try to sit on an object that is being held it forces the object to be dropped.

This also means that if you try to sit on an object being held by another player that they will drop the object.  This may not be the behavior we want.  If not, then it's a one-line fix to change it to only affect you sitting on an item that you are holding.

**Comment by jefforkin** [comment]
Thanks Dave.  I would prefer to try out allowing players to sit on something the other player is holding.  We'll see how problematic that is if they carry people around.  But should be pretty humorous.

**Comment by dwenger01** [comment]
I created a new Issue (201) to address wanting to be carried by the character holding the object.  Since this issue (188) has been addressed, I'll close it for now.
