### ISSUE TITLE
Can't stand from bar

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#189]
User reports:  I got stuck after I sat on the bar table no matter what I did I could not stand up

**Comment by dwenger01** [comment]
Trying to repro this without much success.  I can sit on the bar in front of the bartender (actually I get positioned out in front of the bar), and then I can move and the character stands up.  Do we have anymore info from the user on how they managed to do this?

**Comment by jefforkin** [comment]
I asked the user, and she only said: I don't recall exactly where on the bar I sat I think I was sitting somewhere on the right of the bar table.

**Comment by jefforkin** [comment]
Actually, looking at her Mixpanel analytics, I think she sat on a beer on the bar, that she ordered from the bartender, and could not get up.  See if you can repro that.

**Comment by dwenger01** [comment]
Hmmm. can't seem to repro that either.  I can sit anywhere and stand up in the normal manner (hitting a movement key for example).

Is it possible the player was in chat mode, and that was eating all the movement key presses?

**Comment by jefforkin** [comment]
she wasn't in chat mode, because she was interacting with a bunch of other objects.  let's not worry about this one, unless we hear about it again.

**Comment by dwenger01** [comment]
okie dokie

**Comment by jefforkin** [comment]
maybe this is the same as bug #188: Sitting on what you're holding prevents you from moving.

**Comment by dwenger01** [comment]
Can't repro this, and since issue 188 has been addressed, I'll close this one.
