### ISSUE TITLE
Dashboard for viewing analytics outside of mixpanel

### ISSUE THREAD

**Issue by giantotter** [giantotter/giantotter_public#2]

**Comment by grahamboree** [comment]
What exactly does this entail, and is it really necessary?  It'd be nice but if it's a choice between writing our own front end to mixpanel and going to mixpanel, I think the engineering effort could be better spent elsewhere at the moment.  

If it involves graphing some data from mixpanel or something that they don't graph for us, we could write something really quickly in matplotlib or d3js that might not be ideal, but gives us the data we need.

**Comment by jefforkin** [comment]
Closing.  no longer using mixpanel
