### ISSUE TITLE
Fix project naming across tools and Unity

### ISSUE THREAD

**Issue by giantotter** [giantotter/giantotter_public#20]
- Unity uses the project name passed as a parameter to the game to log things.
- Oscripter uses the project name in the Otter_Projects table in Dynamo.
- Word clustering tool uses the Otter_Projects Dynamo table, when it should be grabbing the list from RDS. This is causing problems for projects without oscript projects.
- Log-processing scripts use the "Project" column in various RDS tables that can get out of sync.

We should unify the naming schemes across projects to prevent name resolution issues. The "project_name" value in the oscript project file should be used when logging from Unity. This name should be all lowercase. The Otter_Projects project name is only for distinguishing oscript projects that use the same AI backend. We should modify the existing RDS tables to reference a new "Projects" table by foreign key, to prevent string mismatching between tables.

**Comment by jefforkin** [comment]
stale, no longer relevant
