### ISSUE TITLE
Sitting on what a character is holding should child the sitter to the object being held

### ISSUE THREAD

**Issue by dwenger01** [giantotter/giantotter_public#201]
Currently, trying to sit on an object being held by another character will fail gracefully.

We'd like to be able to sit on the object being held, which means that:

1) The sitting character needs to become a child of the object being held so that the character can be carried as well.

2) When the character holding the object (and the sitting character) drops the object then the sitting character should go to standing.

3) There will probably be issues with the current sit action trying to path "close enough" to the held object such that it will never think it is close enough to perform the sit.  We need to talk about how this situation should be handled.

**Comment by jefforkin** [comment]
no longer relevant
