### ISSUE TITLE
Setup a build server to check that the current build isn't broken

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#205]
It'd be nice to have a build server set up in such a way that when a change is pushed to github, the build server can try to build the game and run a few tests to verify that things are more or less still working.

The idea is that this will help catch obvious code errors fairly quickly (e.g. code that wasn't checked in).  As we get further along and have more scenarios, we'll want to have some automated tests that get run periodically.  These tests would give us some assurance that changes to the platform aren't breaking specific scenarios, and removes the need to manually test every configuration of every scenario every time we make a change.

Anecdotally, if we had a system like this in place already, it would have helped catch changes that broke Lemelson as those changes were made.

**Comment by jefforkin** [comment]
no longer relevant
