### ISSUE TITLE
Update Unity to use new log categories

### ISSUE THREAD

**Issue by giantotter** [giantotter/giantotter_public#21]
Update the log categories for the appropriate actions, and events in the Unity code to use the new "cai" prefixed categories. This task includes determining which of the existing logged values should be included in these categories.
For a list of the existing log categories, see the wiki here: https://github.com/giantotter/giantotter/wiki/Logging-Format

**Comment by grahamboree** [comment]
Is this still relevant given the recent work on AI and the new logging bot?

**Comment by jefforkin** [comment]
I think we can close this.  I remember talking about categories during the WB project, but can't remember exactly what we were trying to solve with them, and a lot has changed since then.

**Comment by grahamboree** [comment]
:+1:
