### ISSUE TITLE
Facial expressions tied to dialogue lines in oscript

### ISSUE THREAD

**Issue by giantotter** [giantotter/giantotter_public#23]

**Comment by grahamboree** [comment]
@dwenger01 Do we have a way to trigger facial expressions through the new character animation system?

**Comment by dwenger01** [comment]
Hi Graham.
Not expressions per se, but you can control blinking, head movement (nod and shake), and eyebrow movement via the animation manager.  These are independent of any other animations playing, so you can vary them to make a few different expressions.

**Comment by jefforkin** [comment]
I vaguely remember Jason showing us a demo of some basic facial expressions.  Maybe it was just eyebrows, but I thought it was mouth too.  Are you sure he didn't give us anything like to control the mouth?

I'd like to have the animation manager support setting some basic expressions on characters -- neutral, happy, sad, angry, maybe a couple more.  Under the hood, it doesn't matter to me if these are actually facial animations, or a combination of facial feature animations.  But it would be nice to hide the details under the interface.

It would be great to hook these up to play randomly during chat, for now.  Give a higher probability weight to neutral, but occasionally play a different expression.  Just to keep chat interesting to look at.

**Comment by dwenger01** [comment]
Ah yes... Totally forgot that there is a smile animation as well that can be controlled via the animation manager.

**Comment by dwenger01** [comment]
I can hook up some "emotional faces" via the animation manager.  You'd be able to select it via an enum value.
