### ISSUE TITLE
Configure whether players cycle or are static.

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#231]

**Comment by jefforkin** [comment]
Specify through project settings (or somehow in OScript) -- not every project will necessarily be structured this way.

**Comment by grahamboree** [comment]
Changing this task to be more relevant to the current state of things:

The LATB project had a mix of this, but we want to be able to specify per-project whether it should choose roles randomly for a group of randomly chosen actors, or whether it should act more like TRG did, where roles are assigned in-order and don't change.

**Comment by jefforkin** [comment]
Closing.  No plans for multiplayer.
