### ISSUE TITLE
In-game chat is connected to Slack.

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#234]
Separate developer chat UI under the gameplay viewport.  Ideally connected to Slack.  add a dev channel to irc.go.com, and a bot that relays to Slack.

**Comment by grahamboree** [comment]
Slack, unfortunately, doesn't make it easy to listen to messages sent to a specific channel. It instead provides a 'web hooks' system whereby it sends message data as a post payload to a URL you specify.  There are python libraries that help you set up a webserver and listen for and respond to these hook, however it involves writing and deploying externally-visible python web application to do so.
  Posting messages to a channel, however, is extremely simple, and works great.  The result of all of this is that I can get the in-game spectator chat to crosspost to slack without problems, however cross-posting from slack to the spectator chat will require a disproportionate amount of work.
  Given this I'm going to hold off on the slack-to-spectator chat aspect until  we can reevaluate how important it is.  I'd expect it to take about 3 to 4 days to get working.
  An easy alternative would be to connect an IRC client directly, or run the game if you wished to post to the spectator chat.
