### ISSUE TITLE
Find a tool to create a font from a spritesheet

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#239]
Creating our own emoji, or even using existing public domain emojis requires packing them into a font.  Ideally we can find an existing tool that is artist-friendly to do this.

**Comment by dwenger01** [comment]
Use of sprite sheets is accomplished with the TextMesh Pro text object and the Unity sprite sheet editor.  Sprites are treated as text and will scale and position correctly based on font size.
