### ISSUE TITLE
Lemelson: clarify & update end-game instructions

### ISSUE THREAD

**Issue by tomaschko** [giantotter/giantotter_public#251]
Instructions on the final screen say "close your browser tab when you’re done" and "follow us on twitter"… We should delete these. Dan will ask Leigh if she wants to make a specific call to action or next step for Lemelson. In the meantime, potentially replace with instructions to press F10 to quit and return to the main menu...Or just leave it at "thanks for playing"

Also instructions say the text is on the clipboard, but we should add a phrase that says something like "If you want to keep the transcript, open a new text file and click ctrl-v or cmd-v to paste the transcript"

**Comment by tomaschko** [comment]
Student testers also reported not understanding the transcript option at the end. Further impetus to clarify the instructions

**Comment by tomaschko** [comment]
Current instructions: ![screen shot 2015-11-17 at 12 24 19 pm](https://cloud.githubusercontent.com/assets/4423632/11219175/1039273a-8d27-11e5-86d3-e20af30a091d.png)

**Comment by tomaschko** [comment]
Change to:
"Thanks for playing [TBD - Name of Game]!

The game transcript has been automatically copied to your clipboard. To save the transcript so that you can remember what you said in the game, open a new text or document file on your computer or tablet and select 'Paste'.

From the game menu in the top right corner (F10 on Windows or fn+F10 on Mac), you can access the Production Credits and Quit.

Thanks again for playing and good luck with your own inventions!"

**Comment by dwenger01** [comment]
This issue is ready, and just needs to have the TBD defined.
