### ISSUE TITLE
Lemelson / SchoolLife: seal up boundaries of the map

### ISSUE THREAD

**Issue by tomaschko** [giantotter/giantotter_public#258]
Student testers reported "falling through the world" when crossing boundary areas of the game - like closed doors in the school. Walk around all of the outer boundaries to identify any openings then seal them with collision boxes (or some other hack)

**Comment by tomaschko** [comment]
Specific areas to block:
+ Both corners of the fence at the front behind the flag
+ Both front walls of the school building when walking from the inside - you fall out when walking through the wall towards the bathroom
+ Both doors at the end of the offshooting hallways on both sides of the school building
+ The right side of the wall separating the main hallway from the cafeteria

**Comment by jefforkin** [comment]
I added some empty game objects with box colliders to prevent falling through the floor in the areas Dan noted.  It seems that some walls and doors had mesh colliders that did not point to a mesh.  I wasn't sure how to find the mesh to point to, so adding box colliders does the trick for Lemelson.  We should get Jason to fix this stuff in the main branch.
