### ISSUE TITLE
Can't leave a game and start a new one.

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#261]
This is not an issue now, since we only have a single game running, however when we allow for multiple games, there is the possibility of hitting this.

The room naming convention is based on the nickname of the player.  If player 'A' leaves a game in progress in room '#A', that game doesn't end because there are other people playing in it.  When 'A' tries to create a new game, the room bot will attempt to place them in a room named '#A'.

**Comment by jefforkin** [comment]
no longer relevant
