### ISSUE TITLE
Separate UI window for Transcript logging in Unity.

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#276]
The transcript json logging spams the normal Unity Debug.Log Console.  Since it's hard to read, and makes debugging more difficult it'd be nice to have the transcript data recorded in a separate Editor window in Unity.

This is probably really low priority but it'd be nice to have.

**Comment by jefforkin** [comment]
I agree.  Another option would be to have a setting somewhere to toggle on and off transcript logging (locally, but always log it to AWS), and have it default to off.

**Comment by jefforkin** [comment]
no longer relevant
