### ISSUE TITLE
Deployment issues for oscript and the unity binary, and a development oscript environment

### ISSUE THREAD

**Issue by giantotter** [giantotter/giantotter_public#28]
We should have some kind of versioning, and way to change the oscript simultaneously with a build. Also we want to be able to work on an oscript project for a while, and then merge in the changes to the main project in one step. Currently the best we can do is:
1.  Copy the original project
2.  Spend as much time as necessary to modify the copy
3.  Copy the original again as a backup
4.  Push a build and wait for the cloudfront cache to clear.
5.  Delete the original
6.  Copy the new version, giving it the same name as the original
7.  Verify things worked
8.  Delete the projects from steps 2 and 3

Between steps 4 and 6 there is a period of time when the game is totally broken for everyone.

**Comment by jefforkin** [comment]
Once the new staging system is operational, would we consider this issue closed too?

**Comment by jefforkin** [comment]
no longer relevant
