### ISSUE TITLE
Animation system to support gestures and lip flapping while NPC talks

### ISSUE THREAD

**Issue by giantotter** [giantotter/giantotter_public#29]

**Comment by grahamboree** [comment]
@dwenger01 What's the status on gestures?  The characters currently lip-flap and fidgit, but is there a way to get them to gesture while lip flapping as well?

**Comment by dwenger01** [comment]
Right now gesturing is not supported.  It would not be too much work to get this to work.  We'd need:

1) The list of gesture animations to support.
2) Add these animations to a new gesture animation layer.
3) Add an animation variable that we can set to say which gesture to play.
4) Add an API in the animation manager to control this from .cs script.

We'd only play gestures from idle states like sit-idle or the regular idle state.

Lip flapping is independent of gestures or fidgets, so we can play lip flapping together with gestures or fidgets.

**Comment by giantotter** [comment]
Right now, it would be great to get gestures in in any form, and then we can tweak it later on.  When you are able, go ahead and add the new layer with any gesture animations that seem to make sense, and do some randomizing of which plays.

**Comment by dwenger01** [comment]
Do you want to be able to select which gesture to play?  Or just put the character into a gesture idle state that idles, but then plays a gesture occasionally?  I assume this would be the type of thing where we'd say, "hey character, you're going to be having a conversation so go into your idle/gesture state until we tell you you're done having a conversation"... 

Also, which gesture animations do we want to use?

**Comment by jefforkin** [comment]
For a first pass, we do not need to be bale to select.  Just randomly gesture using any animations that seem appropriate.  I don't know what we have.  I only know that over a year ago we made a demo video of Tim (african amer male student) moving his arms while he talks.  Ideally the character would only gesture while lip flapping.  and stand idle while waiting for the player to say something.

**Comment by dwenger01** [comment]
Sounds good.  I'll create a new idle state for conversations.

**Comment by dwenger01** [comment]
Support for gesturing is now in.  i.e. we have a sub-state machine that handles random gesturing.

Note that right now we don't have any working gesture animations.  The current animations pull the character through the floor for the duration of the gesture, so I have not utilized those animations at this time.

Instead, the fidget animations are hooked up to the gesturing state.

**Comment by jefforkin** [comment]
Thanks Dave!  We'll take a look.  So to clarify, are you thinking that the gesture animations are unusable until we get Jason's help?  Or there may be some way to correct them in Unity?

**Comment by dwenger01** [comment]
Hi Jeff.  Yeah I've tried numerous things to try to get the gesture animations working, but so far none of them have panned out.  The issue is that the gesture animations appear to have their root at the pelvis, and not at the feet like the fidgets for example.  So when we play the gestures, the character's root position drops to the position of the pelvis and the animation plays.  There may still be a couple of things I can try to get this to work without having to involve Jason, but I'm quickly running out of ideas.

**Comment by dwenger01** [comment]
My latest patch now correctly plays the gesture animations.  There are a few edge cases that we'll need to talk about how we want to solve for the long term (for example a character shouldn't gesture while holding an object).  For now we don't allow gesturing while holding an object.

**Comment by jefforkin** [comment]
oh nice!  so you were able to fix the root at pelvis issue somehow?

**Comment by dwenger01** [comment]
Yes, there is an offset associated with the y position (as well as rotation and the xz plane).  I found that on a per-animation basis we could adjust the offset to raise up the animating character to match where the other animations position it.  Overall we would like all animations to be created in the same way, but for now we can adjust for any differences.
