### ISSUE TITLE
Lemelson: create "credits" page within the game

### ISSUE THREAD

**Issue by tomaschko** [giantotter/giantotter_public#300]
Pending Lemelson guidance, add production credits language:
+ "Developed by Giant Otter Technologies, Inc. on behalf of the Lemelson-MIT Program" 
+ "Special thanks to Saratoga Springs High School and to [Mike's school]"
+ (c) Lemelson-MIT Program

**Comment by jefforkin** [comment]
Also add appropriate acknowledgement of using AIML chatbot.  Uses this license: http://www.gnu.org/licenses/old-licenses/gpl-2.0.html

**Comment by tomaschko** [comment]
I think we can make this a dialogue box / screen that you can access from the Game Menu (not something that automatically displays at the end of the game)

**Comment by tomaschko** [comment]
[UPDATED] (Still) pending Lemelson guidance on first two points, add production credits language:

* "Developed by Giant Otter Technologies, Inc. on behalf of the Lemelson-MIT Program"
* "Special thanks to Saratoga Springs High School and to [Mike's school]"

* (c) 2015 Lemelson-MIT Program

The software included in this product contains copyrighted software that is licensed under the GPLv3. A copy of that license is [either put a link to the license file (task #320) here or put a description of how to bring up this file]. You may obtain the complete Corresponding Source code from us for a period of three years after this file is no longer available for download, which will be no earlier than 2016-06-01, at the website [http://www.example.com/sources/productnum/ - see task #319].’

**Comment by dwenger01** [comment]
I think it's easier to place a link to the license file (task 320), so I just need to know what the link will be for the file.

Also:

1) What is Mike's School referenced in the special thanks section?

2) I'll need to know the website url referenced by task 319 to show where to obtain the source code package.

**Comment by tomaschko** [comment]
@Dave the terms of the gpl license require that we include the
text embedded in the game. If that's impossible I guess we can link to it
but I would prefer the license be embedded

I'll follow up with Lemelson on #1 today

Jeff will get you #2

**Comment by jefforkin** [comment]
The URL for the source code is:  http://giantotter.com/lemelsongpl

**Comment by dwenger01** [comment]
The only piece left to do is fill in the TBD school information.

**Comment by tomaschko** [comment]
Credits:

"The Lemelson-MIT Program acknowledges 

Williamston High School InvenTeam (Williamston, MI) 
Saratoga High School InvenTeam (Saratoga Springs, NY)
Michael P. Gallagher, Master Educator"
