### ISSUE TITLE
Lemelson: final packaging touches

### ISSUE THREAD

**Issue by tomaschko** [giantotter/giantotter_public#301]
Pending Lemelson guidance, change the settings of the final builds to
+ Reflect the new name of the game
+ Include a more appropriate icon

**Comment by grahamboree** [comment]
Do we have an icon or name for the game yet?  Right now everything is branded as "Young Inventor"

**Comment by tomaschko** [comment]
No this is dependent on Lemelson. We have a request outstanding to them. I'll post here & follow up when we have what we need

**Comment by tomaschko** [comment]
Instructions from Lemelson:
- App display name (short name) is "iAdventures" (short for "Invention Adventures")
- App icon available here: https://drive.google.com/file/d/0BwD0LRIwih9SSVM0LVZrVnlIeHJzWFBiaUxVZUZ4WkdTOVZV/view?usp=sharing
