### ISSUE TITLE
Touch and hold interaction system

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#308]
We had talked about this a while back as a way to do interaction well on mobile.  The idea being that the player would touch and object, hold their finger on it, see some progress indication, and trigger an interaction after holding their finger for a certain duration.  This is a very common paradigm in mobile, and can be seen implemented very well in the app ["streaks" for iOS.](https://itunes.apple.com/us/app/streaks/id963034692?mt=8)

**Comment by jefforkin** [comment]
no longer relevant
