### ISSUE TITLE
Change API crossdomain policies for certain calls to only allow requests from teamtools

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#309]
Currently they allow requests from anywhere.  This is a security risk.  If anyone figures out our API calls, they could do horrible things like delete all users and/or logs and AI data.

There is some element of obscurity to the API calls (you'd have to guess the names of them exactly, which may not be super obvious), but a more likely scenario would be if someone sniffed our network traffic while playing the game.  The tech intern we had this summer actually did this exact thing before he asked us which API calls to make, so it's not very far-fetched.

**Comment by jefforkin** [comment]
no longer relevant
