### ISSUE TITLE
Design: Cue cards in TRG

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#326]
In LATB we had the facilitator advance past the cue cards for everyone.  Should TRG wait for everyone to hit the go button or should it show them for a specific time?

**Comment by jefforkin** [comment]
My vote is that everyone gets to see the cue cards for some set period of time.  A lower priority task could be to add some way to redisplay the cue card through the UI.  And/or always show an abbreviated version on-screen somewhere, to keep people on-task.

**Comment by grahamboree** [comment]
Since we have part of this implemented, I split out the other aspects into their own tasks to facilitate specific discussions and prioritization: #369 and #370
