### ISSUE TITLE
More robust login code

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#339]
Sometimes the login screen displays "Logging In..." forever, and sometimes it clears your saved username and password.  I believe the login code is throwing an exception, which is silently ignored, causing infinite loading screens.  I'm unsure what the cause of clearing the saved credentials is.

**Comment by jefforkin** [comment]
I was seeing issues like this today in the LATB_Demo, but that's the old login stuff.  Are you seeing this in the current codebase?  I can look into it.

The credentials get cleared when login fails.  We could just leave them.  The thinking was that they weren't worth saving if they didn't work for logging in.

**Comment by grahamboree** [comment]
Yeah I saw it today when testing in the main branch and I've seen it pre-LATB when opening two instances too quickly.  I don't think it has anything to do with Stormpath or Playfab.  I think the issues are in our code that drives the login UI.
