### ISSUE TITLE
Chat gets transparent as it scrolls

### ISSUE THREAD

**Issue by giantotter** [giantotter/giantotter_public#34]

**Comment by jefforkin** [comment]
This task really refers to having the chat UI slide in and out.  Also, as new chat arrives, chat bubbles appear and fade away, of the chat UI is not slid out.

**Comment by tomaschko** [comment]
Chat history should fade to invisible when you toggle out of chat

When you re-engage chat, history should return and it should be scrollable (once you have enough entries)

Tab to slide chat in and out should not be necessary

**Comment by grahamboree** [comment]
I changed the chat fading to work as described.  I'm going to leave it to the next playtest to see if people feel that that is enough, or if we should add a background or other visual cues.  I also changed the chat to automatically return you to FPS controls once you say something, so we can try that as well to see if people like it.
