### ISSUE TITLE
Sitting on the bar sits you wherever you're standing, and prevents subsequent movement

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#342]
Repro:
1.  Interact with the bar
2.  Select the sit option
3.  Eventually press w to stand

Expected: 
The character plays the kneel animation (that we don't have yet) and sits on the bar.

Observed:
The character plays the sit animation in-place.  After the animation is complete, pressing any movement key will make the character stand again, however they will be unable to move.

**Comment by grahamboree** [comment]
We've also seen some sitting positions be off in playtests.

**Comment by grahamboree** [comment]
The visual aspect of this specific issue should be fixed with the new non-chair sitting animations.

**Comment by jefforkin** [comment]
no longer relevant
