### ISSUE TITLE
Occasionally, one of the characters will fall through the world on spawn.

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#347]
Not sure what's causing this.  It seems like some kind of race condition, or numerical instability problem.  I think revisiting the spawning code, specifically the floor-finding raycast projection should lead to a culprit.  Unfortunately there's not a solid repro that I've found.

**Comment by dwenger01** [comment]
Hi Graham.  Not sure if this is pertinent, but I have seen this type of issue before on other platforms if an object is spawned such that the ray cast begins inside another object that is penetrating the floor of the world.  In this case the raycast doesn't hit any forward-facing surface.  Again, not sure if this is the case here, but perhaps could be if we have a trigger box or other object that intersects the floor, and we're casting a ray from inside of that object.

**Comment by grahamboree** [comment]
Sweet, thanks.  That makes a lot of sense.  I'll have to take a look and see if that's what's happening, but I'd bet you're right.  :smile:

**Comment by jefforkin** [comment]
hasn't been a problem in a long time.
