### ISSUE TITLE
After reloading, scene missing camera

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#387]
I joined Restaurant as a Waitress. Never added another player.  Waited for timer to expire and reload the scene. Saw cue card.  Scene loaded black, with a message on-screen saying there was no fullscreen camera.

**Comment by jefforkin** [comment]
I've seen this happen again, with a different repro.  Waitress starts a game.  Customer joins.  When cue cards are dismissed, Waitress sees black screen saying there is no fullscreen camera.

**Comment by grahamboree** [comment]
Fixed Friday 1/22
