### ISSUE TITLE
Oscripter should display an error if it fails to save because the file is not valid JSON

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#404]
Right now it hangs on "Saving..." which is not great.  There's a big red X in the left gutter of the editor to indicate the source of the problem, however if it's offscreen it's not exactly clear what's happening.

When Oscripter fails to read the json of a file you just edited, it should display some kind of popup that explains it's invalid, and ideally on what line the problem is.

**Comment by jefforkin** [comment]
no longer relevant
