### ISSUE TITLE
Synchronized game start

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#445]
There are lots of circumstances where player timers are off by anywhere from a fraction of a second to as much as 5 or 10 seconds.  I think a lot of this has to do with how the timers are started.  There really should be a system of handshakes where the players each tell the server that they're finished loading.  The server should then wait for all players to finish loading and then start the cue card countdown timer.  Alternatively, it could only wait for the actors in the scene to load, and then periodically sync up the spectators' countdown timers.

**Comment by jefforkin** [comment]
Closing.  No plans for multiplayer.
