### ISSUE TITLE
Compute most likely listener per speech act

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#447]
The AI system requires one speaker and one listener per speech act.  When the listener of an utterance is ambiguous, the AI system needs to choose the most likely listener out of the list.  To do this, it relies on pre-computed probabilities of listener for each type of utterance.

**Comment by jefforkin** [comment]
Re-opened -- I didn't explain the data well enough.  The speech_acts table will only ever have one row per (speaker-cluster_id) pair.  To compute the occurrence count of each pair, we need do a nested select of the log_data table, which references the observations table, which references the speech_acts themselves.  Log_data is the only table that represents instances of speech_acts.  The observation and speech_act tables only specify the unique possible speech_acts.

**Comment by grahamboree** [comment]
Aaaaaah ok.  That makes sense.

**Comment by jefforkin** [comment]
Thinking a bit more about this.  Instead of storing the default listener for each speaker-clusterId, we should just store the occurrence count for each speaker-cluster-listener tuple.  Then, when given a list of possible listeners, query to find the listener in the list with the max count.  

If no count exists for anyone in the list, or if the list is empty, then return the default listener for the speaker -- which is the highest count for a NULL cluster.  The default is stored as speaker-NULL-listener in the table, and computed from the overall count of how many times a speaker spoke to a listener in log_data.
