### ISSUE TITLE
Change "project" to "domain" in AI DB

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#471]
We currently have 'projects' that contain 'domain data' and behavioral data associated with it.  We want to change this to only refer to "domains" and associate behavior with domains rather than projects.  This will more easily allow for code reuse and makes interacting with the database easier.

**Comment by jefforkin** [comment]
Closing this -- it turns out that having both projects and domains is useful.  We have domains like Office and Restaurant, and then projects within those domains.  Scenarios (e.g. Olivia / Constructive Guidance, and now David) roughly equate to "projects".
