### ISSUE TITLE
Simple ed version shows duplicate timer and Demo Mode after player joins

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#476]
Running Second_Step_Simple on ed server. WHen second player joins, first player does not see "Demo Mode" anymore (correct), but second player does see "Demo Mode".  Both players see two timers overlayed on top of one another.

**Comment by jefforkin** [comment]
duplicate

**Comment by grahamboree** [comment]
For posterity: This was split into #508 and #509
