### ISSUE TITLE
Simplify the Oz dialogue line web site

### ISSUE THREAD

**Issue by tomaschko** [giantotter/giantotter_public#477]
Right now we only have one version of this site - https://s3.amazonaws.com/giantotter/oz/index.html - that we are using for all Oz-type demos of the AI coaching experience. This includes Otto / Slack and SchoolLife / Unity

The file and site are getting complicated to navigate. It would be great to simplify with the following updates:

1) Multiple top-level sites 

and/or

2) Ability to group dialogue into sections that can be shown or hidden as needed (e.g., 
![screen shot 2016-05-11 at 4 47 35 pm](https://cloud.githubusercontent.com/assets/4423632/15195960/2f93f4ce-1798-11e6-887e-6f5c29fa29e7.png) )

Possible groupings are
- By product (Otto vs. SchoolLife) - potentially make these separate top-level sites
- By role play scenario (Olivia vs. others for Otto; Rules of the Game vs. Lunchtime vs. others for SchoolLife) - could be top-level sites or sections within each product site
- By character within scenario (only applies to SchoolLife - there are at least two characters) - probably subsections within the scenario
- By phase of the interaction (e.g., product onboarding, pre-role-play session initiation, role play, role play feedback, post-role-play-feedback session wrap-up) - probably sections within the product site

The goal should be to balance the simplicity of each web site with the number of separate back-end json files that need to be maintained & the complexity of those files. E.g., if possible, we should have only 1 file for pre-role play session initiation for Otto, rather than having to maintain identical versions of those lines across multiple files so that we can have multiple complete sites for each role play scenario

**Comment by jefforkin** [comment]
Aaron's Oz tool addresses these issues.
