### ISSUE TITLE
Resurrect LogViewer

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#486]
- Get it working again.
- Note: we no longer need to support editing logs from the viewer.
- Improve making logs more human readable (since we moved to a json format).
- Allow filtering logs by date, username, gametype. (This may require database changes)

**Comment by grahamboree** [comment]
Not sure if the logging format is nailed down, but we'd need to settle on something before this can get working again.

At this point, is a log just a series of observations?

Is the ideal log viewer just the same as the mental model debugger timeline?

**Comment by jefforkin** [comment]
The log format is 99% nailed down -- it is the format found in the Log_data table in RDS.  Each row is a json set that contains an Observation and a Timestamp.

The ideal log viewer would have a way to filter and select logs on the left, and when one log is selected, it would be rendered in a human-readable format on the right -- rendered vertically like text normally is, from top to bottom, rather than a timeline that's used to look at AI (timeline works well for seeing how observations are grouped into events that sometimes overlap in time).

We no longer need support for editing logs that we added for WB.
