### ISSUE TITLE
Connect Slack Otto back-end to Unity front end

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#491]
For handling multiple SL sessions at once.

**Comment by grahamboree** [comment]
There's some usability issues that this would create.  Currently lots of otto is specific to slack (e.g. message formatting).  How would we handle these kinds of things in a system like this?

**Comment by jefforkin** [comment]
If we ever do this, we would probably have to either create something new that is similar to Otto, or separate out the Slack-specific aspects of Otto.  The idea is that one person could control a character in multiple Unity games.  We most likely won't tackle this one anytime soon if ever.   We can close this and revisit if we ever want it in the future.
