### ISSUE TITLE
Canned dialog tool automatically adds feedback footer

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#496]
Footer should always include links to community, ways to replay, etc.

Just attach predefined footer when someone does ./feedback

**Comment by grahamboree** [comment]
Small note: This behavior is controlled by otto, not by the canned dialogue tool.

**Comment by jefforkin** [comment]
Good point.  But I'm thinking that maybe we could define the footer content in the json file, but not render it in the dialog tool.  Although then we'll need a way to tell Otto where to look for the file, so perhaps there should be a separate data file for Otto.  Main point is that footer should be data driven so that Dan or others can change it.

**Comment by grahamboree** [comment]
Even easier: Add the standard footer text as a canned dialogue option.  The downside is you have to copy it when doing feedback yourself, but it wouldn't require any engineering and you'd have complete control over its contents in a way that's already familiar.

**Comment by jefforkin** [comment]
Good idea.  I would just request combining the footer with ending the feedback.

**Comment by grahamboree** [comment]
Is this still something we'd want with the new feedback system?  Is it something that should be built into that or should otto include a set of standard feedback when sending any kind of feedback?

**Comment by jefforkin** [comment]
I defer to Dan to decide on this one.

**Comment by jefforkin** [comment]
Aaron added a default footer in the new Oz tool
