### ISSUE TITLE
Account authorization for Otto

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#499]
Otto should request username of backend person, or require actually logging in with a giantotter account. Will need this bookkeeping when we start hiring people.

**Comment by grahamboree** [comment]
Is this something we'd just do through slack accounts?

**Comment by jefforkin** [comment]
For the foreseeable future, it makes sense to use Slack for authentication.  If we ever move to a system where Oz is not based Slack (custom UI), then we'll need our own authorization stuff.  We can close this for now, and create a new issue if ever needed.
