### ISSUE TITLE
Make cue cards visible or accessible during gameplay

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#507]

**Comment by dwenger01** [comment]
Hi Jeff.  Should the info button that triggers the instruction box to be displayed be part of the unity scene file, or do you want it defined via oscript?

**Comment by jefforkin** [comment]
The info button should not be defined in oscript.  It should be part of the UI (HUD) that appears in every scene, like the Timer or Settings button, and parts of the Chat UI.  I'm not sure exactly where it should get added, but somehow it should be associated with the Standard UI in the GiantOtter game object in the MainMenu scene.  That UI stuff persists as we switch scenes.

**Comment by dwenger01** [comment]
Sounds good!
