### ISSUE TITLE
Blacklisting bad logs

### ISSUE THREAD

**Issue by giantotter** [giantotter/giantotter_public#52]
We need a system for blacklisting bad log files in dynamo. There is currently a log (f1a489d1ce504554425ac81cf8838ddba10b1f648D1581577C290ABC4) with a ridiculous number of lines in it that breaks the api and every log-manipulation tool. The change in cd0bf70 is a temporary fix for this specific situation and should be removed when a real fix is in place.

**Comment by jefforkin** [comment]
stale. we have a more recent task for managing log importing.
