### ISSUE TITLE
Implement entity reference resolution for Slack

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#521]
When the AI tells a bot to interact with an object, there should be a component in the bot that searches the world state of an instance of that kind of object.

For now, we should only allow resolving things that we observed being spawned during gameplay.  Later we may want to populate the world state with some starting state info about entities that already exist.

**Comment by grahamboree** [comment]
Isn't this how the current WorldState object works?  I'm unclear from the description what additional functionality or changes need to happen.

**Comment by jefforkin** [comment]
Right now we assume any object we ask for is there.  This can lead to a waitress cleaning an infinite number of beers off tables.  I'm suggesting that we only add things to the world state when we see them created (like chef serves a steak).  We would need to start the world state populated with critical static entities, like a chair and table.

**Comment by grahamboree** [comment]
aaaah okay that makes sense.  :)
