### ISSUE TITLE
Slackbot turns on and off while waiting for AI server response

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#524]
When the debugger is enabled, sometimes when I'm talking to the bot, I can see the green circle on the Slack avatar for Joanna turn off and  on.  In these cases the interaction history in Slack ends up missing some of the actions that have happened.  Running with the same inputs without the debugger does not have this problem.

Repro:
In the transcript below, the action for the Chef putting soup on the counter gets dropped when debugger is running.

me:  hello
bot:  hi and welcome
bot:  please take a seat
bot:  I'll be right with you
me:  where should I sit?
bot:  have a seat
bot:  right here
me:  /me siton chair
bot: what you like to start off with an apitizer?
bot: A glass of wine, or a beer?
me:  can i get a tart?
bot: (to chef) nectarine tart
<BUG: missing -- [Chef put a soup on the counter]
[Waitress picked up a soup]
etc.

**Comment by grahamboree** [comment]
Seems to be working now.  Lets re-open if we see it again.
