### ISSUE TITLE
Add flags to Sessions in DynamoDB

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#542]
We would like to flag sessions to ignore when importing logs into AI RDS database.

The issues is that once Otto is updated to log data, it will always log data, even when we are just running quick tests to make sure everything works.

Can we add a flags column to the Sessions table?  And an API call to set a flag.  Store flags in a Json dictionary, so we can add other flags as desired later.

**Comment by jefforkin** [comment]
An alternative could be to set the ignore flag in logs in RDS, after importing.  But I would prefer to be able to filter imports, so that during development we can repeatedly blow away the RDS database and reimport logs, without having to re-flag them after import.

**Comment by grahamboree** [comment]
This task has been changed to "Create an API call that can set a label on a session".  We decided it's redundant to have both labels and flags on a session.
