### ISSUE TITLE
Update Oscript projects with new spawn nodes

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#558]
Let's update some existing oscript projects to set them up for the new spawn node system.  Leave the original positional data in the scripts so that they remain backward compatible for now, until we update all branches with a new build.

Projects to update:
Dev and Prod:  Restaurant
Education:  Education_Demo, Education_Simple, Second_Step, Second_Step_Simple

**Comment by dwenger01** [comment]
Hi Jeff,

I know the dev project files can be reached via:  http://giantotterteamtools-dev.elasticbeanstalk.com/oscripter

What are the paths to the prod and education projects?

**Comment by jefforkin** [comment]
For education swap the -dev for -ed. For production just oimt the -dev
completely
On Jul 5, 2016 11:54 PM, "David Wenger" notifications@github.com wrote:

Hi Jeff,

I know the dev project files can be reached via:
http://giantotterteamtools-dev.elasticbeanstalk.com/oscripter

What are the paths to the prod and education projects?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/giantotter/giantotter_public/issues/558#issuecomment-230665173,
or mute the thread
https://github.com/notifications/unsubscribe/AG-njNuSaZ9ViX4Fi9p_GIQdUtW7ElvIks5qSycMgaJpZM4JASzp
.

**Comment by jefforkin** [comment]
Omit that is...

**Comment by dwenger01** [comment]
One last question Jeff...  Is it okay to update the project settings for the education projects on the -ed server?  The changes would be just to associate spawn point information with scene roles, so they'd be innocuous until a build with the new code to support spawn points is made.
