### ISSUE TITLE
Shorten Otto channel names

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#560]
It seems like Slack has a max length for channel names.  For example, starting a channel for andrew-demo created the channel:
# z_coachotto_andrew-de

The "coachotto_" part is superfluous, and takes a lot of characters, so we should just do #z_andrew_demo (or whatever the username is).

The truncation of andrew-demo wasn't a big deal, but when I tried to start a demo for a different Andrew at andrew-demo2, that session started in the same channel that was used for a different Andrew.

**Comment by tomaschko** [comment]
I think the "coachotto" refers to the team name ... so if we're engaging
with a user from athenahealth it would be "z_athenahealth_andrew"

I wonder if there is a way to incorporate some kind of number or unique id

**Comment by jefforkin** [comment]
Oops, Dan is correct. so maybe we should just reverse the order such that the team name comes last, and the more unique part of the channel names comes first -- where the user name is more unique.  Obviously this wont sort as nicely, but we'll have fewer naming collisions. For example, we might end up with z_andrew_athen and z_andrew2_athe, if we had two andrews at athenahealth. 
Dan?

**Comment by jefforkin** [comment]
Ok, let's address naming collisions, while keeping things simple.  Since Dan feels sorting by team is important, here are my suggestions:
- Remove the underscore between z and team name.
- truncate team name in the channel name to 3 characters.  We'll see in the future how often this causes problems and adapt as necessary.
- When we setup new demo accounts, I recommend naming them like mike3-demo instead of mike-demo3.

**Comment by tomaschko** [comment]
works for me
