### ISSUE TITLE
Otto is not logging

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#562]
Not catastrophic because we have everything logged in Slack, but for some reason the dev LogViewer does not show any olivia logs more recent than 7/1/16, even though we have run many demos since then.

**Comment by grahamboree** [comment]
You're looking in the dev teamtools.  The dev/prod switch means that the live otto you're using isn't using the dev dynamo tables anymore.  You should be able to import from both prod and dev though, so once it's in RDS, there'll be no difference.

Just verified that there are logs from 7/6, 7/7 and 7/8 in the prod logviewer.

**Comment by jefforkin** [comment]
I thought of that and tried prod team tools but did not see a label for
olivia. I can take a look later, but can you double check it works?

**Comment by grahamboree** [comment]
This is what I'm seeing... does it look like all the data that was missing?

<img width="708" alt="screen shot 2016-07-10 at 11 44 29 am" src="https://cloud.githubusercontent.com/assets/1139220/16714526/c0b4749a-4693-11e6-8a67-cc58fb8ce01d.png">

**Comment by jefforkin** [comment]
Ok cool I think that look correct. I'll look closer later but seems good
