### ISSUE TITLE
Otto's .label command should add new labels

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#563]
When we use the .label command to label a session, Otto should add a new label to dynamo if that label does not yet exist.

I just did a test with a disposable label, oliviatest, and could not see the log in LogViewer until I manually added oliviatest to dynamo's labels table.  I think this was the problem I was having with the more recent olivia logs, when we moved otto to prod -- initially there was no olivia label.

**Comment by grahamboree** [comment]
Good catch.  Looks like I added the code for this in the wrong function, which would explain why you weren't seeing logs in prod's logviewer.
