### ISSUE TITLE
Main Roleplay: AI repeats line "Whew, I'm glad that's over..."

### ISSUE THREAD

**Issue by tomaschko** [giantotter/giantotter_public#595]
If I wait to reply to "Whew I'm glad that's over", Olivia repeats the same line

**Comment by jefforkin** [comment]
v14 (removed label)

**Comment by jefforkin** [comment]
Similar repetition seen in v18:
- 2016-09-14 17:12:57 , 2016-09-14 21:23:48,  2016-09-14 17:03:15 
  olivia repeats opening whew
  -  2016-09-14 17:03:15  repeats 'numbers good'
