### ISSUE TITLE
Main Roleplay: adjusting timing for statements kicking off roleplay

### ISSUE THREAD

**Issue by tomaschko** [giantotter/giantotter_public#597]
Now, it's
- Olivia: "Hi dan"
  <pause>
- Olivia: "Whew I'm glad that's over..." 

I'm tempted to interrupt in the middle with "Hi Olivia" or something 

Instead, it should be snappy, like if they were part of the same turn "Hi Dan. Whew I'm glad that's over...!"

**Comment by jefforkin** [comment]
v14 (removed label)

**Comment by jefforkin** [comment]
fixed in v15
