### ISSUE TITLE
Main Roleplay: Olivia skipping to the end of the scenario

### ISSUE THREAD

**Issue by slaeuchli** [giantotter/giantotter_public#598]
Example: 
Olivia: It wasn't too bad though was it? 
Me: No it wasn't too bad but it undermines your presentation. Maybe next time we could practice before your presentation
I am happy to help you
Olivia: Thanks. See you later!

**Comment by jefforkin** [comment]
v14 (removed label)

**Comment by jefforkin** [comment]
duplicate or 594
