### ISSUE TITLE
Combine json data for Oz & runtime Tip generation

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#615]
Chris implemented a solution for generating tips at runtime for the Botcamp demo, introducing a new data file, so that we wouldn't disturb the existing Oz tool.  We should now merge the data structures needed for Tips from human operators, and Tips from Otto's AI.

This task should include adding any support not currently present for defining rules:
- Two tips can be paired to be mutually exclusive.
- How should we prioritize tips (like if we only want to present 3, but 5 are valid)?
- How do we control how many positive and negative tips get displayed?
- What is the default tip, if somehow none were valid?
- We should also use data to control the tips intro utterance.  e.g. only say "That was :100: when there are no negatives.

**Comment by Nesciosquid** [comment]
The Oz side of this is done. We need to implement the tag/tip analysis code on the Python side. 

We may actually want to write the tag/tip analysis as an API call instead, and do it in Oz as a request to the server, so we don't have to have the same code written in two places.
