### ISSUE TITLE
Add to Slack button is live

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#616]
We already have the authentication systems necessary to support the Add to Slack button.  The remaining work includes setting up web pages to host the button (possibly password protected for now) and the page users get directed to that has instructions for getting started with Otto.

And possibly creating a tool that allows us to send the equivalent of an Add to Slack button via email to someone.

**Comment by Nesciosquid** [comment]
The 'Add to Slack' button is a UI shortcut that makes it easy for anyone to add Otto to their teams.

The install token system I set up is designed to solve the problem of needing a public page with such a button on it. 

What I had in mind for now is sending specific people an email with the tokenized install link in it -- if you want to style that link to look like the 'Add to Slack' button, that's totally doable!

The other way to do this (safely) is to generate an intermediate page that _looks_ like a public page with the normal Add-to-Slack button, but is actually just a passthrough for the token.

**Comment by jefforkin** [comment]
I don't have a preference on email vs web page -- you and Dan should make the call.  But either way I think the new users will need to get redirected to a web page with basic getting started info.   Completing this task really means that we've documented whatever approach we'll take to have people add Otto to teams, and Dan has tested the whole process.

**Comment by Nesciosquid** [comment]
Sounds good to me!
