### ISSUE TITLE
Migrate to Docker-based API servers on EB

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#619]
We needed to use Docker to handle scientific Python library dependencies.

**Comment by Nesciosquid** [comment]
Production server is now running live on a docker EB. 

Matt and I have come up with a plan that should allow us to update and deploy docker images to EB with zero downtime.

It works like this:
- We maintain two of each EB environment -- `A` and `B`, separated by one version. One of them (the current one) has the correct URL that our applications link to. Let's say that's `A`.
- When we want to update, we build a new docker image and deploy it to whichever of the two environments has the incorrect URL. (In this case, that's `B`.) 
- If the update succeeds and tests show no issues, we swap the URLs of the two environments, such that the correct URL now points to `B` and the incorrect one to `A`. 
- This has a number of helpful effects:
  - No downtime during the upgrade.
  - Always have a running version of the 'previous' version of the API, so if we screwed something up, we can rollback with no delay.
  - Convenient time to run tests on the environment before it gets swapped over.
