### ISSUE TITLE
Otto detects when new teams add Otto

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#621]
Right now Otto discovers teams on startup by scanning a Dynamo table, or when an operator uses the addteam command.

We need some way for Otto to dynamically detect when 3rd parties add Otto to a team.

**Comment by Nesciosquid** [comment]
Turns out, Otto already does this! It scans at regular intervals to detect new teams. We could modify Otto to act as web server and send it a command when a user adds Otto via Slack, but we don't need to do that right now.
