### ISSUE TITLE
Separate AI, API, and Otto

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#627]
Currently it is not safe to deploy a new API serverm without also redploying Otto.  This is due to the fact that the AI is changing often, and is tightly coupled to both the API and Otto.  By separating the AI (and moving the MM within -- see #625), we can do frequent AI updates without needed to reploy Otto or the API.  As part of this task, we should have separate build scripts and maintain separate build numbers for each deployment, manually for now.

**Comment by Nesciosquid** [comment]
Moving this to closed, since we changed our minds about how the API and AI work together. AI and Otto are still separated, though, so that's good!

I think it's worth opening a new issue with a more clear goal.
