### ISSUE TITLE
Picking up the trashcan totally obscures the camera

### ISSUE THREAD

**Issue by giantotter** [giantotter/giantotter_public#63]
When the trashcan is picked up, it obscures the camera, so that you aren't able to click on anything to put it down.

The solution to this and other holding-related issues is probably to add a "hold point" or "hold offset" to all objects that you can pick up. Being able to specify both a position and orientation offset would be useful for positioning items

**Comment by dwenger01** [comment]
Is there a preferred solution to this problem?  Ideally we would attach an invisible 3D game object to the trashcan, for example, that defines the "grab position and orientation".  Is this the approach you're thinking of, or do you want a component that just has an offset and a rotation?  I think we would then store this information in the prefab for the object.  Thoughts?

**Comment by grahamboree** [comment]
I think the most flexible solution is what you're describing, with an invisible 3d object.  We can use the `localPosition` and `localOrientation` of the invisible object to offset the actual object when it's attached to the player.  We'd definitely want to store this in the prefab of the object and modify the object pickup code to add the offset.

**Comment by dwenger01** [comment]
Sounds good.  That's the approach I'll take.  Thanks Graham.

**Comment by dwenger01** [comment]
This should be fixed as of 6/29 with my "generalized object gripping" patch.
