### ISSUE TITLE
Keypad 'Enter' key does not submit chat text

### ISSUE THREAD

**Issue by giantotter** [giantotter/giantotter_public#64]
Repro:
1. Run the game and enter the restaurant level
2. Type a chat message in the chat input field.
3. Hit the enter key on the numeric keypad. Observe the '\n' inserted in the input field

Expected: Both enter keys work identically.

**Comment by tomaschko** [comment]
I still observe this issue when playing on MAC

**Comment by grahamboree** [comment]
This is a bug in the OSX version of the webplayer.  It does not happen in the editor.  I'm currently working on a workaround
