### ISSUE TITLE
Separate legacy API functionality

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#653]
We should not need the API for anything, once we move the AI to its own server.

The new web tools interact directly with AWS resources.  We have legacy tools (OScripter) that will still need the API.  For those we will continue running an API, until we can phase them out.

**Comment by Nesciosquid** [comment]
I basically decided that the direct-to-AWS interactions were a Bad Idea and have nearly completely moved away from them, so I'm closing this one out.
