### ISSUE TITLE
Script to build an environment

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#660]
Currently, we do not capture the schemas of Dynamo tables anywhere.  We just create them through the AWS dashboard, or on the fly from code.  We should have a script that creates the correct Dynamo tables.

Is there anything else the script should create, in terms of AWS?

And, is should this be the same task as issue 648 -- should (and can) the same script setup Dynamo locally and/or on AWS?

**Comment by Nesciosquid** [comment]
I think we decided we're moving away from this in favor of better local environments.
