### ISSUE TITLE
There should be no default environment

### ISSUE THREAD

**Issue by ottermatt** [giantotter/giantotter_public#663]
Let's not default the environment to dev anymore. By explicitly setting the environment we can avoid lots of unintentional change errors. Also: when dev goes away, what would we default to?

It's probably worth doing this right and making the current_config complain loudly when someone tries to use it uninitialized.

**Comment by jefforkin** [comment]
Aaron had a good point that his recent changes to environment.py rely on overriding a default config, which is a good design (I think).  And we concluded that there should be a default environment BUT all of the URLs it references should be localhost.

**Comment by ottermatt** [comment]
The more I think about this, the more I'm convinced that explicitly
specifying the environment is the right thing to do. The only value in
having a default environment, that I can see, is convenience and the
downside is that I am definitely going to shoot myself in the foot a couple
of times because I didn't specify the environment. But I guess it will only
be my foot and not the company's, so that's OK.

If you are going to have a default config, though, having it reference
localhost is the right thing, though.
