### ISSUE TITLE
Giantotter game displays new version available, then quits

### ISSUE THREAD

**Issue by KurtWoloch** [giantotter/giantotter_public#667]
I tried to start the Giantotter game (AKA Restaurant game) today, and got the message that a new version would be available. After going to the Giantotter homepage, however, a new version is nowhere to be found. Also there's no info on what happened to the game. I think this is a bit inconsistent (though, sadly, not unusual). There should be some info on what's going on for your old players.

**Comment by jefforkin** [comment]
Sorry Kurt, we have had to shelve development on the GroupPlay restaurant game for the time being to focus on other projects.  Thank you for letting us know of the issue.  We have removed the download page for now while the project is inactive.
