### ISSUE TITLE
f_asian idle animation incorrectly handles the model's hair and eyebrows

### ISSUE THREAD

**Issue by giantotter** [giantotter/giantotter_public#68]
The hair vertices are not animated correctly for the standing idle animation. The eyebrows are nearly always twitching and screwed up.

This is the only student model we have that has a wig that uses the wig bones in the model. The other student characters' wig (if they have one) is attached directly to the head bone or a spine bone. We may need to talk with Jason to ensure that the hair is attached as it is intended, and/or determine if there is something in the animation mask that needs to be set to fully support the IK hair.

Ok, I emailed Jason with everyone CC:ed. If he can't help us figure it out right way, we might want to just use a different female model for now. The Asian female is special, with the long hair. The teacher would make a good waitress.

**Comment by jefforkin** [comment]
Assigning this to Dave to investigate if there is anything we can do to fix the eyebrows without JayonZ's help.

**Comment by dwenger01** [comment]
Eyebrow issue is now fixed - the eyebrow animations were set to looping when they should not have been.

**Comment by jefforkin** [comment]
cool dave.  could looping be causing the hair issue too?  or is that different, because it's somehow using IK?  Either way, we can move this bug to backlog for now, since we're not actively using f_asian right now.

**Comment by dwenger01** [comment]
I can look into that, but I don't think looping is related to the hair thing.  I think it might be something going on with IK, but I'll need to triage that issue better to know for sure.
