### ISSUE TITLE
Roleplay returns to Main Menu when user quits

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#680]

**Comment by dwenger01** [comment]
This currently works by default.  On Quit you are taken back to the MainMenu oscript and can select a different scenario to run.

**Comment by dwenger01** [comment]
One question on this Jeff.  Will the scenario synopsis data be shown when the player chooses to quit a scene?

**Comment by jefforkin** [comment]
Let's just keep it simple -- if the player quits it goes back to the main menu.  not sure how we would get the tips if the player didn't complete (if that's what you mean).  The only thing we might want is a confirmation, are you sure you want to end the scene and return to the main menu -- Ok / cancel.   I do think we should do that.

**Comment by dwenger01** [comment]
Sounds great Jeff.  Yeah, I was just wondering if there was some way I needed to request tips for the conversation up to that point.  But I think we're on the same page.  Thanks!

**Comment by dwenger01** [comment]
Exiting the scene will confirm that you want to quit, and if so will take you back to the main menu.
