### ISSUE TITLE
SL Tips UI popup

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#683]
At the end of the roleplay, the game will display personalized tips to the user, like Otto does.

We need a UI window to pop up on the right side of the screen, with a button to hide/show it, and a button to copy the tips to a file.

Jeff will provide a sample Json file of what the AI will send to display the tips.

**Comment by dwenger01** [comment]
Jeff, can you describe where you want the hide/show button to be placed and how you expect it to work?  I assume the button is placed somewhere independent of the panel, since if it's in the panel and you select "hide" then you'll have no way to show the panel again.

**Comment by jefforkin** [comment]
We might need Jason's help to make it look right, but I'm imagining a
circle with a down arrow in the middle of the bottom or the collapsed UI.
and then when the UI expands, the circle has an up arrow, and is again in
the middle of the bottom of the expanded UI.

**Comment by dwenger01** [comment]
So both the info panel, as well as the tips, will be able to both be hidden/shown?

**Comment by jefforkin** [comment]
When scenario starts, info panel is on screen, top right, contracted.  It
has a down arrow to expand.

Tips panel is initially hidden.  When scenario gets to point at end where
tips are presented, info window gets hidden.  Tips window appears in its
place.  Tips window is a fixed size -- same size as expanded info window.
Tips has button at bottom that says Got It, which dismisses Tips window.

Finally, we pop up a new panel that covers most of screen with general
antibullying advice.  Click ok to end scene and return to main menu.

**Comment by dwenger01** [comment]
This work is done except for hooking into the end-of-scenario event.
