### ISSUE TITLE
SL Info UI expands/contracts

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#684]
Dave has prototyped a SL info window, that gets displayed from the (i) button.  I think it would be better to have a very brief info window persist in the top right, and expand with a click.  The brief info has very concise, summarized cues, and the expanded gives a more complete explanation.

**Comment by dwenger01** [comment]
Hi Jeff.  Do you want me to remove the (i) button entirely?

**Comment by jefforkin** [comment]
Yes, let's remove the (i) button completely.  Not needed since the idea now is that the info window stays on-screen, and expands/contracts.
