### ISSUE TITLE
Final list of scenes, locations, actors

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#699]
Dan and Sarah will provide a list of scenarios, locations, actors.  Exact cue card text can be finalized later, but getting the locations and actors will allow us to focus Jason and Dave to set things up for each scene.

**Comment by tomaschko** [comment]
Script with staging directions: https://docs.google.com/presentation/d/1R9hHYVhSPYxYcZ6fyXSum6woNVMH1zoxauqFsX_JkoQ/edit?usp=sharing
