### ISSUE TITLE
SL main menu displays 5 scene buttons

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#700]
Main menu should have a button to start each scene.  There will be 5 scenes.  User can start any scene at any time -- no scripted ordering (like we had in GroupPlay).  Initially we can set it up so that all 5 map to the same scene, until we have more than 1 scene.

**Comment by dwenger01** [comment]
This is all handled in the oscript mainmenu code.  I've stubbed out 5 buttons now that all execute the same command to load the one scenario that is currently defined.

This has been updated in the dave_education_simple oscript on both the education and development servers.
