### ISSUE TITLE
Start SL at splash screen then main menu, no login

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#701]
Currently SL starts at a login screen.  we want to start at a splash screen like Lemelson.  The splash screen has a button to start the game, taking the user to the main menu.

If removing the login screen scene is problematic (or non trivial), it may be easiest to copy the login scene, and change a copy of the UI to look/behave like a splash screen.  We can use the AccountManagerPassthrough class under the hood to skip Playfab authentication.

**Comment by dwenger01** [comment]
The initial patch to support this has been pushed.  It redirects the login button from the login dialog to call a new method that bypasses network login.  A subsequent patch will address the implementation of the splash screen for this issue.
