### ISSUE TITLE
Show general anti-bullying best practices at end of each scenario

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#709]
After the player has completed the chat dialogue in a scene, and received their tips, there should be a button that says "Got it!" (or something).

When clicked, the scene will end, but will first show one more pop-up displaying some general tips that are the same every time for each scene (scripted in oscript per scene), advising the player of things to think about in the future related to bullying.

**Comment by dwenger01** [comment]
The scripting work for this is basically in, but will need to be tested when we actually can get an official end-of-scenario alert.

**Comment by dwenger01** [comment]
Note:  These tips will come from the oscript file, on a per-scenario basis I assume.

**Comment by jefforkin** [comment]
We should hard-code in oscript these general anti-bullying best practices at the end of each scenario.  Each scenario has their own general tips.

The tips are specified in:  https://docs.google.com/presentation/d/1R9hHYVhSPYxYcZ6fyXSum6woNVMH1zoxauqFsX_JkoQ/edit#slide=id.g18b4802396_0_5

And repeated here...

Scene 1:
Remember
- There are many different ways you can help someone who is being bullied. You should select the approach that feels right and comfortable to you.
- If you aren’t sure how to intervene in a situation where someone is being bullied you can always ask a friend for help.
- You should always talk to an adult if you, or anyone else, feel unsafe. 

Scene 2:
Remember
- Bullies often want attention. You can create a distraction to focus attention away from the bully and onto something else.
- Only intervene if it feels safe
- You should always talk to an adult if you, or anyone else, feel unsafe.

Scene 3:
Remember
- Bullies often want attention. Don’t support them by giving it to them.
- Try acting disinterested, or telling them straight out that their behavior isn’t entertaining or funny
- Never egg on a bully by laughing or joining in on the teasing
- You should always talk to an adult if you, or anyone else, feel unsafe. 

Scene 4:
Remember
- You can help someone who is being bullied by spending time with them at school. Sitting with them at lunch, inviting them to play games or talking to them at recess can help a lot
- Calling or texting someone outside of school is a great way to let them know they can talk to you about the situation
- If you’re not sure the best way to be a friend to someone being bullied, try asking them what you can do to help
- Encourage them to talk to a trusted adult and offer to help start that conversation if they’re unsure how to do that

Scene 5:
Remember
- You can talk to an adult in person or leave them a note, whichever makes you more comfortable
- An adult could help stop bullying from continuing so it could be good to talk to someone as soon as you witness bullying happening
- The more adults involved, the better. You don’t need to talk to just one person- you can reach out to teachers, counselors, nurses, parents, anyone you think may help.

**Comment by jefforkin** [comment]
Here are the absolute FINAL general tips to show:

SCENE 1: Defining Bullying
- :bouquet: There are many different ways you can help someone who is being bullied. You should select the approach that feels right and comfortable to you.
- :speaking_head_in_silhouette: If you aren’t sure how to intervene in a situation where someone is being bullied you can always ask a friend for help.
- :raising_hand: You should always talk to an adult if you, or anyone else, feel unsafe.

SCENE 2: Help Him Get Away
- :sleuth_or_spy: Bullies often want attention. You can create a distraction to focus attention away from the bully and onto something else.
- :warning: Only intervene if it feels safe for you to do so. Your safety matters, too!
- :raising_hand: You should always talk to an adult if you, or anyone else, feel unsafe.


SCENE 3: Help Him Get Away
- :see_no_evil: Bullies often want attention. Don’t support them by giving it to them.
- :sunglasses: Try acting disinterested, or telling them straight out that their behavior isn’t entertaining or funny
- :innocent: Never egg on a bully by laughing or joining in on the teasing.
- :raising_hand: You should always talk to an adult if you, or anyone else, feel unsafe.


SCENE 4: Be His Friend
- :open_hands: You can help someone who is being bullied by spending time with them at school. Sitting with them at lunch, inviting them to play games or talking to them at recess can help a lot.
- :telephone_receiver: Calling or texting someone outside of school is a great way to let them know they can talk to you about the situation.
- :speaking_head_in_silhouette: If you’re not sure the best way to be a friend to someone being bullied, try asking them what you can do to help.
- :information_desk_person: Encourage them to talk to a trusted adult and offer to help start that conversation if they’re unsure how to do that.


SCENE 5: Tell and Adult
- :memo: You can talk to an adult in person or leave them a note, whichever makes you more comfortable.
- :raising_hand: An adult could help stop bullying from continuing so it could be good to talk to someone as soon as you witness bullying happening.
- :information_desk_person: The more adults involved, the better. You don’t need to talk to just one person- you can reach out to teachers, counselors, nurses, parents, anyone you think may help.
