### ISSUE TITLE
Fix how images are linked from S3

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#721]
Currently we hard code where on S3 to find resources, like the image for an Otto scenario prompt.  We need to better organize media, and only store a URL in the data/content.

**Comment by Nesciosquid** [comment]
I kinda hacked this one. I'm now checking to see whether the string looks like a URL, passing it along if so, otherwise padding it to point at the legacy S3 bucket.

We'll need to adjust the old logs to use the new format eventually, I think.
