### ISSUE TITLE
Tags are not always leading to correct Tips

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#738]
In the log linked below note:

On line 49, the user says something that gets bound to log data ID 1219

The database says that 1219 is tagged with *TIP1_DIRECTLY_POINT_OUT_ISSUE

Tips at line 113 tell the user:
You never clearly stated what the issue with Olivia's presentation was.

https://tools.tinyotter.com/logviewer/labels/staging.Otto.Webchat.ai.v33-0.olivia/sessions/e663cf9d8b184a07801f348f89249d6e?env=staging

**Comment by Nesciosquid** [comment]
Fixed. It was a configuration issue with the olivia `feedback.json` file, which was looking for tags which didn't exist because we never went back to modify the data to use `strong` and `weak` tags.
