### ISSUE TITLE
Clustering tool performance issues

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#741]
Sarah says:
Once I hit around 10% of utterances clustered the tool slowed down significantly. After 15% it got really, quite slow. I've been avoiding using the work space as much as possible as that's what seems to slow it down more than clicking utterances into clusters using the tools on the left hand side of the screen. The search functions also slow it down. I've tried it on a couple of different computers so I don't think it's my machine-- the slowing down also seems to be related to number of clusters versus number of utterances as it's fine at the beginning and slows down as I add more clusters.

**Comment by Nesciosquid** [comment]
This was (primarily) an issue with the way clusters were looking up which utterances belonged in them. I fixed it by changing the underlying data model to give clusters a list of which utterances they contain, which speeds things up a lot.

There are almost certainly other things we can do to improve performance, but this took the tool from 'unbearably slow' to 'usable'.
