### ISSUE TITLE
Data surgery for Mr. Jones

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#742]
We put in a fix to let Sarah correctly cluster utterances with "Mr. Jones", but we still need to repair the processed logs, such that the clustered utterances map to observations in logs.

**Comment by Nesciosquid** [comment]
Adding Chris to this, since I need him to collaborate with me to do comparisons between old vs. new versions of the processed utterances. (And he needs to fix the parser to allow the Mr./Mrs./Ms./Dr. terms)
