### ISSUE TITLE
Olivia moves too quickly during tutorial role play

### ISSUE THREAD

**Issue by cmward** [giantotter/giantotter_public#748]
See lines 19-24: https://tools.tinyotter.com/logviewer/labels/chris.Coach%20Otto.Slack.ai.36-3.olivia/sessions/12f12e4b4aaa4d8fb101839c9fa8b0f2?env=staging

**Comment by jefforkin** [comment]
There is a related more recent bug, where if Olivia moves through the tutorial too fast, and the user doesn't get enough turns, the tutorial never thinks it is complete.

Repro:
answer how was your weekend with: "it was pretty good. how was yours"
Olivie moves immediately from good good....  to, see you later.  User doesn't get enough turns to recognize the level 1 event as complete.
