### ISSUE TITLE
Lookat action doesn't work for all objects correctly.

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#76]
For example, looking at the bill causes you to zoom through the register and look at the floor.

**Comment by grahamboree** [comment]
Assigning to Dave and moving to in-progress because I think he's already working on this right now as part of his camera system.

**Comment by dwenger01** [comment]
Zoom is now performed with FOV changes on the camera, so it is no longer possible for the camera to pass through the object being looked at.
