### ISSUE TITLE
Disable chat text bubble fading in SL

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#764]
The chat bubble fading is working strangely when I test it with AI.  The top bubbles stay, and the more recent ones fade.

For now I think we should just disable fading.  

If we have time for polish, we might allow the chat to fade if no one says anything for some period of time, and then fade back in when the user clicks on the text input.

**Comment by dwenger01** [comment]
Currently, the chat text fades out when the user looks around, and fades back in when the user stops rotating the camera.  Otherwise the chat does not fade.
