### ISSUE TITLE
Re-enable TTS for SL

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#783]

**Comment by dwenger01** [comment]
This appears to be working now; however, there is an issue with the incorrect audio being played.

My guess is that we need to have a unique room id from run to run to ensure that we don't reuse old tts lines from previous runs.

**Comment by jefforkin** [comment]
hmm, ok lets try generating a GUID for the room ID and see if that solves it.  weird that I didn't see this issue.  I would think that we would just overwrite audio files with the same names before trying to play them.

**Comment by dwenger01** [comment]
Maybe I don't have permissions to overwrite them?  Not sure.  I ran this morning and then looked on S3 after the fact.  None of the .wav files had today's date, and it was clear it was re-using what was there.  If you could try running then we could determine if your run creates new files in the SchoolLifeRoom folder on S3.

**Comment by jefforkin** [comment]
Ah, I see what you mean.  didnt seem to update for me either.  maybe that is what those 500 errors are all about.  maybe the API itself doesnt have permission to write to S3.  I was testing running SL against the staging API.  Not sure, need to investigate more later.

**Comment by dwenger01** [comment]
Closing this ticket for now.  The issues described here will be addressed in the TTS tweaks ticket.
