### ISSUE TITLE
Add credits UI to SL

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#791]
We need to add a credits UI, linked from the F10 menu UI.  Needs to include the NSF grant # blurb, and not much else.

We will figure out the specifics of the text...

**Comment by dwenger01** [comment]
How much text is in the credits?  If it's a lot then we'll need to change the credits panel to be a next / prev set of panels instead of a scrollable panel like I have now.  Lemelson used the next / prev panels.

**Comment by jefforkin** [comment]
The credits will be minimal.  we mostly just need room for the NSF required couple of sentences.  We can fit them in whatever space is currently set up.

**Comment by jefforkin** [comment]
Here is the text for the credits:

This material is based upon work supported by the National Science Foundation under Grant Number 1456093.  Any opinions, findings, and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the National Science Foundation.

© Copyright 2017 Giant Otter Technologies, Inc.

**Comment by jefforkin** [comment]
Also, let's remove the scroll bar from the credits window.
