### ISSUE TITLE
Remove SL screenshot feature

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#815]
we would like to remove the screenshot feature, and just export text transcripts.

**Comment by dwenger01** [comment]
A little more work needs to be done if we don't want raw emoji or other formatting text artifacts in the raw synopsis text.

**Comment by jefforkin** [comment]
Dont worry about the emoji formatting, or other formatting.  just exporting the raw text is fine.  but would be nice to export to the same directory as the executable, or a subfolder named logs or something.
