### ISSUE TITLE
Performing a lookat action on a far-away object causes the camera to be permanently incorrectly offset

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#82]
Interact with a faraway object and select "look at".  When the character gets to within the reach distance, they'll start performing the lookat action, but the camera start position will be incorrect because the character will still be moving when the lookat starts.  As a result, when the lookat ends, the character has stopped moving, but the camera is returned to an incorrect position.  Again, assigning this to Dave and marking as in-progress because he's already replacing this whole action with a FOV zoom.

**Comment by dwenger01** [comment]
This appears to be fixed with Graham's recent changes.

**Comment by grahamboree** [comment]
Awesome.  I fixed a few minor things with the GOTO action and the "reach" distance that were exacerbated by the new controls.  I can see how it would have caused this issue as well.
