### ISSUE TITLE
Use web chat (and microtask chat) with other scenarios

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#823]
Aaron, can you document how you would suggest adapting web chat to use with other scenarios / domains?

Would be great to get suggestions for both, a quick & dirty solution, no matter how ugly, and a longer term solution.

**Comment by Nesciosquid** [comment]
Set this up to work with query parameters for the `/ottoChat` and `/microtasks/chat` endpoints.

Will include documentation with the rest of the webtools doc stuff.
