### ISSUE TITLE
SL cue card tweaks

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#827]
- Cut the word "And" in front of "Both of you are students at Mayville Middle School."

- Make the "to-do" items on the cue cards bullets or a numbered list

- Add a bullet for Be His Friend

**Comment by dwenger01** [comment]
Jeff, are you saying the bolded items (I think those are the to-do items) should have an asterisk or something in front of them?

**Comment by jefforkin** [comment]
If TextMeshPro would support actual bullets via markdown, then we would like to bullet the to-do items, if we can fit that vertically.  If that's not possible, let's just leave them bolded, as is.

**Comment by dwenger01** [comment]
TextMesh Pro doesn't support bulleting or numbering via markdown.  I should be able to fit all the bolded to-do items as bullet points on separate lines.

**Comment by jefforkin** [comment]
hey Dave, here is the final decision on formatting the cue card text -- look at this google doc, and use it as a guide for what to bold.

I think you already have most of this in place, but want to point out:
Scene 1 has been slightly reworded, and ends with a numbered list, where each item is on a separate line, if possible with TextMeshPro.

And, Scene 4 now has bolded items.  Forgot to bold them previously.

No changes to the other scenes.  All documented here:  https://docs.google.com/document/d/1qmlnI6bsaKvzb5XElMV6FWXfxby5dBDaY2nBQdUpxII/edit#
