### ISSUE TITLE
Use consistent button styling for Begin button

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#830]
The BEGIN button the splash screen should use the same UI styling as other buttons.

**Comment by dwenger01** [comment]
Hi Jeff.  What specifically do you want changed?

The color of the button?

The color of the button text?

Something else?

**Comment by jefforkin** [comment]
we want the BEGIN button to look like the buttons on the main menu screen.  White-ish buttons with a 3D-like styling, and dark gray text.
