### ISSUE TITLE
Refine SL cue card layout

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#834]
Make the cue card bigger if needed to accommodate...

Show thumbnails for all characters in the scene, and add caption text for their names below the image.

Center the thumbnails above the rest of the text.

Remove the text for "You are Amy" since it already says that in the highlighted bar at the top.

Remove text that says "Start scene for everyone"

Change button text to say "Start Scene"

**Comment by dwenger01** [comment]
Jeff.  Have a look at the current changes in the latest code/resources, and let me know what tweaks you would like.  I think there may be some characters we don't want to acknowledge in the cue card, but I leave that decision to you.

**Comment by jefforkin** [comment]
This looks perfect Dave.  Only change is that I don't think we should include the Male Extra on the cue card.  Just the named characters.

**Comment by dwenger01** [comment]
Good.  My thoughts exactly regarding the "Male Extra" character.  I'll take care of that.
