### ISSUE TITLE
Indicate what object the player is interacting with

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#84]
Right now it can be a bit unclear what object you're interacting with,.  It'd be nice to have some kind of object highlight shader or other way of indicating what the player clicked on.

**Comment by grahamboree** [comment]
We've decided to add standard FPS controls similar to Gone Home.  Implemented in #85.

**Comment by grahamboree** [comment]
I have a shader working for this but there are some issues with how it interacts with the Restaurant's baked lighting.  I have to do more research into how I can use Unity's lightmaps in the highlight shader, as well as draw the highlight.

Alternatively, or as an interim solution, I could just increase the emission color of the object so that the tint of the object changes.  This is the same effect used in Gone Home, though their levels were generally fairly dark, so the highlight was more visible than it probably would be in the restaurant

*With the object highlight:*
![highlighted](https://cloud.githubusercontent.com/assets/1139220/8554701/3a9202f8-24b9-11e5-88af-5a2a5209f57c.jpg)

*Without the object highlight:*
![not_highlighted](https://cloud.githubusercontent.com/assets/1139220/8554714/478f22ba-24b9-11e5-9bfe-9c93d3ba8f85.jpg)

**Comment by grahamboree** [comment]
Notes for myself:

http://www.alanzucconi.com/2015/06/10/a-gentle-introduction-to-shaders-in-unity3d/
http://forum.unity3d.com/threads/extend-standard-shader.297682/
https://gist.github.com/jimfleming/5937437

**Comment by jefforkin** [comment]
Short-term:  will discuss via email our immediate options to highlight objects and characters.

Longer-term:  eventually get outlining working.

**Comment by grahamboree** [comment]
Remove grey-ing out of interaction icons as well.  If the object is too far away, don't highlight it or allow clicking on it.
