### ISSUE TITLE
Make sure SL Tips can handle when there are no bad tips

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#847]
When testing SL AI in Slack, I noticed a case where there we no negative tips.  Double check this will show up correctly in SL.

Might be best to always have a default +/- tip, in the config file

**Comment by dwenger01** [comment]
I've definitely seen this work correctly when there were no negative tips.  Let me know if you need me to change anything on the Unity end to handle this in a different way.

**Comment by jefforkin** [comment]
Closing.  We decided it wont work well for anti-bullying to make up default tips.
