### ISSUE TITLE
Sitting does not work in multiplayer

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#92]
When a character sits down in TRG we don't see that action performed in the other character's world.  So if I'm the waitress and the customer decides to sit down then from the customer's point of view he is now seated, but from the my point of view he is still standing.

**Comment by dwenger01** [comment]
It appears that OtterControlsSit is written only from the server-side.  It has code there to handle camera control as well as handling of input.  The code needs to be generic enough to handle when either the server-side or client-side character decides to sit or to stand.

**Comment by jefforkin** [comment]
This is now fixed, aside from the rotation issue on the remote clone.  Dave's fixes work, and the Goto spamming that was causing issues has been resolved in the WASD controller.
