### ISSUE TITLE
Picking up one object while holding another causes the originally held object to float

### ISSUE THREAD

**Issue by tomaschko** [giantotter/giantotter_public#93]
As the waitress, I was holding the cutting board and tried to pick up the wine bottle from the bar. When I picked up the bottle, I automatically put down the cutting board (as expected) - except the cutting board did not rest on the bar, but instead floated a few "feet" above it. I reproduced the same effect with the wine bottle and a vase at the table closest to the bar

**Comment by grahamboree** [comment]
Interesting.  I think it's trying to figure out where exactly to place the object (doing the raycast down to the surface) before the other object has been picked up.  I recently modified this code a bit and probably introduced this.  Thanks for the find.
