### ISSUE TITLE
Add emoji

### ISSUE THREAD

**Issue by tomaschko** [giantotter/giantotter_public#94]
Emoji / emoticons are hugely popular in all chat-based apps for their expressiveness. Adding them to our keyboard could be a relatively simple way to give users much more fine-grained control over behavior of their character 

Eventually we could tie specific emojis (smile, frown, kiss, etc.) to animations

Some thought would have to be given to how we handle for them for the AI, but we can work that out

**Comment by grahamboree** [comment]
Unity fully supports unicode font rendering, however the default fonts don't have support for nearly any emoji.  

There's some things on the asset store that we could use:
https://www.assetstore.unity3d.com/en/#!/content/27267

Or we could implement our own system with an emoji sprite sheet and the "rect" rich text keyword.
http://answers.unity3d.com/questions/964411/unity5-emoji-support.html

**Comment by tomaschko** [comment]
It might make sense to sync up with this common format to start - http://www.emoji-cheat-sheet.com/

Not sure how easy it is to go from there to unity though

**Comment by tomaschko** [comment]
http://emojione.com/developers

**Comment by jefforkin** [comment]
Just occurred to me that we might want to integrate this task with #23 -- facial expressions on avatars during chat.  

here is my proposal:
- if chat input has no emoji, we use random weights to occasionally play a random facial expression, at a low frequency, just to add a little life and variety.
- if chat input does include an emoji, we look up associated meta data describing the affect of the emoji, and use it to set the avatar's facial expression.
- if there are multiple emoji, or emoji with no clear affect (e.g. a slice of pizza), we randomly pick an affect and play it.  But when there is an emoji, we always play a facial expression of some kind.

**Comment by dwenger01** [comment]
Support has been added.
